#!/usr/bin/env bash
#-------------------------------
# Script    : Charlotte
# Versão    : Desenvolvimento
# Autor     : Nicholas Affonso
# Ciado em  : 17 01 2023
# Licença   : GNU/GPL v3.0
#-------------------------------
# Descrição : 
#
# Charlotte é um programa que auxilia
# no processo de pós instalação
# de um ambiente linux debian
#-------------------------------
# Uso: 
#
# De permissão de execução ao arquivo charlotte e
# inicie o programa com comando ./charlotte
#
# Leia o documento README para mais informações
#-------------------------------

#--------| INÍCIO VARIÁVEIS |--------#
line="\n---------------------------------\n"
user=( $(getent passwd 1000 | awk -F':' '{ print $1 }') )
charlotte=$(dirname "$0")
#---------| FIM VARIÁVEIS |----------#

clear
# Verifica se o usuário é root
[ "$EUID" -ne 0 ] && {
	printf "$line"%c"Por favor, rode como root$line"
	exit 1
}

apt update -y
apt upgrade -y
apt autoremove

# Instalando progamas de CLI
apt install -y $(cat $charlotte/pkgs/cli)

# Instalando drivers
apt install -y $(cat $charlotte/pkgs/amdDrivers)

# Instalando ambiente gráfico
#apt install -y $(cat $charlotte/pkgs/gui)

# Instalando pacotes multimidia CLI
apt install -y $(cat $charlotte/pkgs/multimidia)

# Instalando fonts
mkdir -p /home/$user/.local/share/fonts
cd /home/$user/.local/share/fonts && curl -fLO https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/DroidSansMono/DroidSansMNerdFont-Regular.otf

# Clonando repositórios
#cd /home/$user

#git clone https://github.com/NicholasAffonso/dotfiles.git

#git clone https://www.github.com/asdf-vm/asdf.git
#git clone https://www.github.com/tmux-plugins/tpm
  
#echo ". /home/$user/asdf/asdf.sh" >> /home/$user/.bashrc
#echo ". /home/$user/asdf/completions/asdf.bash" >> /home/$user/.bashrc
  
exit 0
